## Step 1: Prepare training text
This sample paragraph provides the text the model will learn from.

In [152]:
text="""John woke up early in the morning and looked outside the window. 
The sky was clear, and the streets were quiet. 
He decided to make a cup of coffee before starting his work. 
After breakfast, John opened his laptop and checked his emails. One message was from his friend David, who invited him to visit a new restaurant in the city. 
John replied that he would be happy to join him later in the evening."""

## Step 2: Count words
`split()` separates the text into words, and `len()` counts the total number of words.

In [153]:
len(text.split())

75

## Step 3: Install TensorFlow
TensorFlow provides the machine-learning tools required to build and train the model.

In [154]:
!pip install tensorflow

26050.92s - pydevd: Sending message related to process being replaced timed-out after 5 seconds


## Step 4: Import preprocessing tools
`Tokenizer` converts words into numbers. `pad_sequences` makes sequences the same length.

In [155]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

## Step 5: Create the tokenizer
A tokenizer creates a dictionary that maps each word to a unique number.

In [156]:
tokenizer = Tokenizer()

## Step 6: Build the vocabulary
`fit_on_texts()` reads the training text and creates the word-to-index mapping.

In [157]:
tokenizer.fit_on_texts([text])

## Step 7: View the vocabulary
`word_index` displays the numeric index assigned to every word.

In [158]:
tokenizer.word_index

{'the': 1,
 'his': 2,
 'john': 3,
 'in': 4,
 'and': 5,
 'to': 6,
 'was': 7,
 'he': 8,
 'a': 9,
 'him': 10,
 'woke': 11,
 'up': 12,
 'early': 13,
 'morning': 14,
 'looked': 15,
 'outside': 16,
 'window': 17,
 'sky': 18,
 'clear': 19,
 'streets': 20,
 'were': 21,
 'quiet': 22,
 'decided': 23,
 'make': 24,
 'cup': 25,
 'of': 26,
 'coffee': 27,
 'before': 28,
 'starting': 29,
 'work': 30,
 'after': 31,
 'breakfast': 32,
 'opened': 33,
 'laptop': 34,
 'checked': 35,
 'emails': 36,
 'one': 37,
 'message': 38,
 'from': 39,
 'friend': 40,
 'david': 41,
 'who': 42,
 'invited': 43,
 'visit': 44,
 'new': 45,
 'restaurant': 46,
 'city': 47,
 'replied': 48,
 'that': 49,
 'would': 50,
 'be': 51,
 'happy': 52,
 'join': 53,
 'later': 54,
 'evening': 55}

## Step 8: Split the text
The text is divided into separate lines or sentences for processing.

In [159]:
text_split=text.split("\n")

## Step 9: Display the split text
This shows the individual text sections created in the previous step.

In [160]:
text_split

['John woke up early in the morning and looked outside the window. ',
 'The sky was clear, and the streets were quiet. ',
 'He decided to make a cup of coffee before starting his work. ',
 'After breakfast, John opened his laptop and checked his emails. One message was from his friend David, who invited him to visit a new restaurant in the city. ',
 'John replied that he would be happy to join him later in the evening.']

## Step 10: Convert sentences to numbers
Each word in a sentence is replaced with its tokenizer index.

In [161]:
for sentence in text_split:
    print(tokenizer.texts_to_sequences([sentence])[0])

[3, 11, 12, 13, 4, 1, 14, 5, 15, 16, 1, 17]
[1, 18, 7, 19, 5, 1, 20, 21, 22]
[8, 23, 6, 24, 9, 25, 26, 27, 28, 29, 2, 30]
[31, 32, 3, 33, 2, 34, 5, 35, 2, 36, 37, 38, 7, 39, 2, 40, 41, 42, 43, 10, 6, 44, 9, 45, 46, 4, 1, 47]
[3, 48, 49, 8, 50, 51, 52, 6, 53, 10, 54, 4, 1, 55]


## Step 11: Create n-gram training sequences
Each sequence contains previous words followed by the word the model should predict.

In [162]:
input_sequences = []

for sentence in text_split:
    token_list = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

## Step 12: Display training sequences
This displays the generated input sequences and their target words.

In [163]:
input_sequences

[[3, 11],
 [3, 11, 12],
 [3, 11, 12, 13],
 [3, 11, 12, 13, 4],
 [3, 11, 12, 13, 4, 1],
 [3, 11, 12, 13, 4, 1, 14],
 [3, 11, 12, 13, 4, 1, 14, 5],
 [3, 11, 12, 13, 4, 1, 14, 5, 15],
 [3, 11, 12, 13, 4, 1, 14, 5, 15, 16],
 [3, 11, 12, 13, 4, 1, 14, 5, 15, 16, 1],
 [3, 11, 12, 13, 4, 1, 14, 5, 15, 16, 1, 17],
 [1, 18],
 [1, 18, 7],
 [1, 18, 7, 19],
 [1, 18, 7, 19, 5],
 [1, 18, 7, 19, 5, 1],
 [1, 18, 7, 19, 5, 1, 20],
 [1, 18, 7, 19, 5, 1, 20, 21],
 [1, 18, 7, 19, 5, 1, 20, 21, 22],
 [8, 23],
 [8, 23, 6],
 [8, 23, 6, 24],
 [8, 23, 6, 24, 9],
 [8, 23, 6, 24, 9, 25],
 [8, 23, 6, 24, 9, 25, 26],
 [8, 23, 6, 24, 9, 25, 26, 27],
 [8, 23, 6, 24, 9, 25, 26, 27, 28],
 [8, 23, 6, 24, 9, 25, 26, 27, 28, 29],
 [8, 23, 6, 24, 9, 25, 26, 27, 28, 29, 2],
 [8, 23, 6, 24, 9, 25, 26, 27, 28, 29, 2, 30],
 [31, 32],
 [31, 32, 3],
 [31, 32, 3, 33],
 [31, 32, 3, 33, 2],
 [31, 32, 3, 33, 2, 34],
 [31, 32, 3, 33, 2, 34, 5],
 [31, 32, 3, 33, 2, 34, 5, 35],
 [31, 32, 3, 33, 2, 34, 5, 35, 2],
 [31, 32, 3, 33, 2, 34

## Step 13: Find the longest sequence
The maximum sequence length is required to pad all sequences consistently.

In [164]:
max_len = max([len(x) for x in input_sequences])

## Step 14: Display the maximum length
This shows the length of the longest generated sequence.

In [165]:
max_len

28

## Step 15: Pad the sequences
Zeros are added before shorter sequences so every sequence has the same length.

In [166]:
padded_sequences = pad_sequences(input_sequences, padding='pre', maxlen=max_len)

## Step 16: Display padded sequences
This displays the sequences after padding has been applied.

In [167]:
padded_sequences

array([[ 0,  0,  0, ...,  0,  3, 11],
       [ 0,  0,  0, ...,  3, 11, 12],
       [ 0,  0,  0, ..., 11, 12, 13],
       ...,
       [ 0,  0,  0, ..., 10, 54,  4],
       [ 0,  0,  0, ..., 54,  4,  1],
       [ 0,  0,  0, ...,  4,  1, 55]], shape=(70, 28), dtype=int32)

## Step 17: Create input data
`x` contains all words except the final word in each sequence.

In [168]:
x = padded_sequences[:,:-1]

## Step 18: Create target data
`y` contains the final word that the model must learn to predict.

In [169]:
y = padded_sequences[:,-1]

## Step 19: View input data
This displays the numeric input sequences used for training.

In [170]:
x

array([[ 0,  0,  0, ...,  0,  0,  3],
       [ 0,  0,  0, ...,  0,  3, 11],
       [ 0,  0,  0, ...,  3, 11, 12],
       ...,
       [ 0,  0,  0, ..., 53, 10, 54],
       [ 0,  0,  0, ..., 10, 54,  4],
       [ 0,  0,  0, ..., 54,  4,  1]], shape=(70, 27), dtype=int32)

## Step 20: View target data
This displays the expected next-word indexes.

In [171]:
y

array([11, 12, 13,  4,  1, 14,  5, 15, 16,  1, 17, 18,  7, 19,  5,  1, 20,
       21, 22, 23,  6, 24,  9, 25, 26, 27, 28, 29,  2, 30, 32,  3, 33,  2,
       34,  5, 35,  2, 36, 37, 38,  7, 39,  2, 40, 41, 42, 43, 10,  6, 44,
        9, 45, 46,  4,  1, 47, 48, 49,  8, 50, 51, 52,  6, 53, 10, 54,  4,
        1, 55], dtype=int32)

## Step 21: Check input dimensions
`shape` shows the number of training examples and input sequence length.

In [172]:
x.shape

(70, 27)

## Step 22: One-hot encode the targets
`to_categorical()` converts each target index into a one-hot encoded vector.

In [173]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(y, num_classes=56)

## Step 23: Inspect an encoded target
This displays the one-hot vector for the first target word.

In [174]:
y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.])

## Step 24: Import model components
These Keras classes are used to create the neural-network model.

In [175]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense, Bidirectional
model = Sequential()

## Step 25: Build the model layers
The embedding layer represents words as vectors, the LSTM learns word order, and the Dense layer predicts the next word.

In [176]:
model.add(Embedding(input_dim=56, output_dim=10, input_length=max_len-1))
model.add(LSTM(150))
model.add(Dense(56, activation='softmax'))

/Users/ankitdwivedi/Documents/Design_Patterns/.venv/lib/python3.13/site-packages/keras/src/layers/core/embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


## Step 26: Compile the model
The loss function measures prediction errors, while Adam updates the model weights.

In [177]:
model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=['accuracy'])

## Step 27: Build and summarize the model
This initializes the model and displays its layers and number of parameters.

In [178]:
model.build((None, max_len-1))
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ (None, 27, 10)         │           560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_6 (LSTM)                   │ (None, 150)            │        96,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 56)             │         8,456 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 105,616 (412.56 KB)

 Trainable params: 105,616 (412.56 KB)

 Non-trainable params: 0 (0.00 B)

## Step 28: Check target dimensions
This confirms the shape of the one-hot encoded target data.

In [179]:
y.shape

(70, 56)

## Step 29: Train the model
`fit()` trains the model for 200 epochs using the prepared sequences.

In [180]:
model.fit(x, y, epochs=200)

Epoch 1/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 5s 40ms/step - accuracy: 0.0286 - loss: 4.0260  
Epoch 2/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0857 - loss: 4.0203
Epoch 3/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0714 - loss: 4.0161
Epoch 4/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0714 - loss: 4.0102    
Epoch 5/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.0714 - loss: 3.9995
Epoch 6/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0714 - loss: 3.9719
Epoch 7/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0714 - loss: 3.9267
Epoch 8/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0714 - loss: 3.8989
Epoch 9/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0714 - loss: 3.8884
Epoch 10/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0714 - loss: 3.8799
Epoch 11/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0714 - loss: 3.8735
Epoch 12/200
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.071

## Step 30: Define test text
This is the starting word provided to the trained model.

In [187]:
test_data="John"

## Step 31: Convert test text to numbers
The test word is converted into its tokenizer index.

In [189]:
test_data_index = tokenizer.texts_to_sequences([test_data])

## Step 32: Display the test index
This confirms the numeric representation of the test word.

In [190]:
test_data_index


[[3]]

## Step 33: Pad the test input
The test sequence is padded to match the input format expected by the model.

In [191]:
padded_test_data = pad_sequences([test_data_index], maxlen = max_len, padding="pre")

## Step 34: Generate predictions
The model returns a probability for every word in the vocabulary.

In [196]:
predictions = model.predict(padded_test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step


## Step 35: Find the most likely word
`argmax()` finds the index with the highest prediction probability.

In [225]:
import numpy as np
index = np.argmax(predictions)
index

np.int64(11)

## Step 36: Display prediction confidence
This retrieves the probability assigned to the selected prediction.

In [226]:
value = predictions.flat[index]
value

np.float32(0.1351628)

## Step 37: Display all probabilities
This shows the prediction probability for every vocabulary word.

In [227]:
predictions[0]

array([2.43595878e-06, 4.98887757e-03, 1.70117877e-02, 1.08827464e-01,
       1.65376160e-02, 6.62565650e-03, 2.59087589e-02, 2.17896514e-02,
       7.27398694e-03, 1.81212241e-03, 8.68331845e-05, 1.35162801e-01,
       4.49696258e-02, 5.92764392e-02, 9.00688756e-04, 5.50539873e-04,
       3.18969745e-04, 3.78063960e-05, 1.51231652e-02, 1.82303060e-02,
       6.79523917e-04, 7.64493248e-04, 8.88244133e-04, 1.15316480e-01,
       3.39620956e-03, 3.84602376e-04, 2.06706885e-04, 8.57292689e-05,
       1.11071611e-04, 1.36160612e-04, 6.53786265e-05, 3.69291843e-06,
       1.34760395e-01, 5.95563129e-02, 1.75479054e-03, 1.63621793e-04,
       1.55623871e-04, 1.26428800e-04, 3.04534205e-05, 2.79023279e-05,
       5.20254362e-05, 4.35200818e-05, 1.84312357e-05, 4.92794534e-05,
       2.76312767e-05, 4.88285077e-05, 8.66874761e-05, 3.76876742e-05,
       1.29263848e-01, 6.37462437e-02, 1.72449532e-03, 5.13134117e-04,
       1.98553229e-04, 8.07869365e-05, 3.33774551e-05, 2.61461500e-05],
     

## Step 38: Convert the index to a word
`index_word` converts the predicted numeric index back into readable text.

In [240]:
next_word = tokenizer.index_word.get(11)
next_word

'woke'